ALTER TABLE Organizations
ALTER COLUMN [Description] NVARCHAR(MAX);

ALTER TABLE Accounts
ALTER COLUMN Region NVARCHAR(MAX);

ALTER TABLE Appointments
ALTER COLUMN Note NVARCHAR(MAX);

ALTER TABLE Diagnostics
ALTER COLUMN Note NVARCHAR(MAX);

ALTER TABLE Medicines
ALTER COLUMN Note NVARCHAR(MAX);

ALTER TABLE Services
ALTER COLUMN Note NVARCHAR(MAX);